name = "PeriodicARModels"
uuid = "8fb27774-97dd-4e71-ba3d-ec1f27cf7f43"
authors = ["ArnaudG0649 <arnaudcmc@hotmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Loess = "4345ca2d-374a-55d4-8d30-97f9976e7612"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RegularizationTools = "29dad682-9a27-4bc3-9c72-016788665182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.10.15"
ConcreteStructs = "0.2.3"
DataFrames = "1.8.1"
DataFramesMeta = "0.15.6"
DataInterpolations = "8.6.1"
Dates = "1.11.0"
Distributions = "0.25.122"
FileIO = "1.17.1"
ForwardDiff = "1.2.2"
GLM = "1.9.0"
JLD2 = "0.6.2"
LinearAlgebra = "1.11.0"
Loess = "0.6.4"
Optimization = "5.1.0"
OptimizationOptimJL = "0.4.7"
OrderedCollections = "1.8.1"
Polynomials = "4.1.0"
Random = "1.11.0"
RegularizationTools = "0.6.0"
Statistics = "1.11.1"
StatsBase = "0.34.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
